version: '3'
services:
  # App
  todo:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - default
      - todo

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  todo:
